### ISSUE TITLE
Environment Variables are not being passed

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/mautic#20]
### Mautic Version

5.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

While I am testing the new code with Redis and Supervisord I noticed that environment variables are not getting passed. 

Here are the steps I am taking in the testing server: 

1. Installed `supervisord` and configured the process to work as follows
````
command=php  /var/www/html/bin/console messenger:consume email_transport --memory-limit=16G
user=ubuntu
numprocs=2
startsecs=0
autostart=true
autorestart=true
stopasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/logs/supervisord.log
process_name=%(program_name)s_%(process_num)02d
stopwaitsecs=3600
environment=MESSENGER_CONSUMER_NAME=%(program_name)s_%(process_num)02d
````
2. In `local.php` I configured messenger like this 
```
'mailer_messenger_dsn' => 'redis://127.0.0.1:6379/messages?auto_setup=true&tls=false&consumer=%env(MESSENGER_CONSUMER_NAME)%',
```

3. That caused an error because `MESSENGER_CONSUMER_NAME` was not found

4. Inside `console` I added a `var_dump(getenv())`  but I could not find `MESSENGER_CONSUMER_NAME`, so it confirmed that there is a problem in this area.

5. To make sure that the env var is not being passed, I created a PHP file with `getnev()` and I could see the environment variable

6. I think the problem is related to how symfony reads the configuration

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pasxel** [comment]
Should be fixed by [b72583b](https://github.com/mabumusa1/mautic/pull/24/commits/b72583bb226eca6dda44361902ec59e85550d85d)
