### ISSUE TITLE
Mautic fails Silently find Mailer Configuration Variable is not present 

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/mautic#6]
### Mautic Version

5.0.x series

### PHP version

7.4

### What happened?

Mautic did not produce an error message when I tried to test the connection 

![image](https://user-images.githubusercontent.com/12627658/153754255-5dbc3e48-5a89-4029-b3d0-a4720cdffda7.png)

### How can we reproduce this issue?

1. On `local.php` remove the configuration variable `mailer_dsn`
2. Clear cache
3. log in to Mautic admin panel, then try to test the connection it will show a success message, although it should show an error because the connection string in `mailer_dns` does not exist.
4. Expected Bahrvior an error message showing

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pasxel** [comment]
Should be fixed by c4e1182caa76a776787b890f3b23b75058229659
