### ISSUE TITLE
Irrelevant Config variables

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/mautic#7]
### Mautic Version

5.0.x series

### PHP version

7.4

### What happened?

There are multiple configuration variables that should not be in the configuration file anymore, since this is breaking change PR, it is fine to remove them. we will handle them in the upgrade

Those variables are stored in `app/bundles/EmailBundle/Config/config.php`, I think we need to remove them. 

```
'mailer_transport'               => 'smtp',
'mailer_host'                    => '',
'mailer_port'                    => null,
'mailer_user'                    => null,
'mailer_password'                => null,
'mailer_encryption'              => null, //tls or SSL,
'mailer_auth_mode'               => null, //plain, login or cram-md5
'mailer_amazon_region'           => 'us-east-1',
'mailer_amazon_other_region'     => null,
'mailer_spool_path'              => '%kernel.root_dir%/../var/spool',
'mailer_spool_msg_limit'         => null,
'mailer_spool_time_limit'        => null,
'mailer_spool_recover_timeout'   => 900,
```

The variables that need to stay: 
```
'mailer_dsn'                     => 'null://null',
'mailer_messenger_dsn'           => 'sync://',
'mailer_spool_type'              => 'memory', //memory = immediate; file = queue
```

We need a way to keep the UI as is but translate the inputs into connection string that is stored correctly inside `local.php`, I think @pasxel shared there is a function that can do this task.

### How can we reproduce this issue?

No steps to reproduce

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pasxel** [comment]
Should be fixed by c1ca9acc37b3144be9c60bdaef614307c2ce733a
