### ISSUE TITLE
File Spool should be removed

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/mautic#8]
### Mautic Version

5.0.x series

### PHP version

7.4

### What happened?

Queue mode settings should be replaced with settings that match the connection string to `Symfony/messenger`.

Queue mode itself should remain, but the settings & code related to `file spool` should be removed

![image](https://user-images.githubusercontent.com/12627658/153754595-4c429f4d-7a62-40b6-9538-437085b3cab8.png)match

### How can we reproduce this issue?

No relevant code

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pasxel** [comment]
Should be fixed by c1ca9acc37b3144be9c60bdaef614307c2ce733a
