### ISSUE TITLE
Public URL callbacks not working

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/mautic#9]
### Mautic Version

5.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

- Url Callback is an important part of the system, they are removed or not working anymore 
- There are callback classes that got removed from the folders and the config files. let's keep them as we will migrate other transports in the future so we need those call backs.

### How can we reproduce this issue?

- Changed your email settings to use SES SMTP or SES API 
- Try to visit `https://domain.com/mailer/amazon_api/callback` or `https://domain.com/mailer/amazon/callback` 
- Error 500 will be displayed

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pasxel** [comment]
should be fixed by 9586b90d0d5ba4630c2a5a8a6b11d1844d31e059
